### ISSUE TITLE
 SSL not available for this app yet.

### ISSUE THREAD

**Issue by nickfmc** [rehmatworks/serverpilot-letsencrypt#43] opened 2020-05-30 03:27 UTC
I had an old version of the script, and when my cert expired and didn't update I updated my script to the latest version but now just get this error when trying to install ??

**Comment by bfjare** [comment] 2020-06-22 17:36
I am getting this as well...

A possible DNS issue found. XXX.io may be pointing to a wrong IP (XXX.XXX.XXX.XXX)
A possible DNS issue found. www.XXX.io may be pointing to a wrong IP (XXX.XXX.XXX.XXX)
SSL not available for this app yet.

I can confirm the ip addresses are correct

**Comment by bfjare** [comment] 2020-06-22 17:37
If i try to add or remove all I get

list index out of range

**Comment by conorbarclay** [comment] 2020-07-01 17:12
> If i try to add or remove all I get
> 
> _list index out of range_

+1. Getting the same when I try `getcerts` or `removecerts`.

**Comment by onetrev** [comment] 2020-07-17 11:19
Same here on my attempt to remove and `getcerts` again. It used to work perfectly when I first started using this updated script. This [other bug](https://github.com/rehmatworks/serverpilot-letsencrypt/issues/44) is a duplicate of this one I believe.

**Comment by rehmatworks** [comment] 2020-07-19 05:49
Please check my last reply in #44

**Closed** 2020-07-19 06:53 UTC
